dist: bionic
language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: true

# command to install dependencies
install:
  - pip install colcon-common-extensions flake8 pytest PyYAML
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
  - sudo apt -qq update
  - sudo apt -qq install python3-rosdep
  - sudo rosdep init
  - rosdep update

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=15 --max-line-length=127 --statistics
  # useful variables for building
  - export COLCON_EVENT_HANDLING="--event-handlers desktop_notification- status-"
  # prepare workspace
  - mkdir -p ros_ws/src && ln -s $TRAVIS_BUILD_DIR ros_ws/src && cd ros_ws
  - export ROS_DISTRO=dashing
  - rosdep install -y -q -n --from-paths src --ignore-src --rosdistro $ROS_DISTRO
  - source /opt/ros/$ROS_DISTRO/setup.bash

# command to run tests
script:
  - colcon build $COLCON_EVENT_HANDLING
  - colcon test $COLCON_EVENT_HANDLING
  - colcon test-result
  # show logs of broken tests
  - for file in $(colcon test-result | grep "\.xml:" | cut -d ":" -f1); do echo "$file:"; cat $file; done
