// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef ROSIDL_TYPESUPPORT_MICROXRCEDDS_TEST_MSG__MSG__NOT_ENOUGHT_MEMORY_TEST_HPP_
#define ROSIDL_TYPESUPPORT_MICROXRCEDDS_TEST_MSG__MSG__NOT_ENOUGHT_MEMORY_TEST_HPP_

#include "rosidl_typesupport_microxrcedds_test_msg/msg/detail/not_enought_memory_test__struct.hpp"
#include "rosidl_typesupport_microxrcedds_test_msg/msg/detail/not_enought_memory_test__builder.hpp"
#include "rosidl_typesupport_microxrcedds_test_msg/msg/detail/not_enought_memory_test__traits.hpp"

#endif  // ROSIDL_TYPESUPPORT_MICROXRCEDDS_TEST_MSG__MSG__NOT_ENOUGHT_MEMORY_TEST_HPP_
